language: r
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
  - r: release
  - r: devel
  allow_failures:
  - r: devel

branches:
  except:
  - dev

warnings_are_errors: true

notifications:
  email: false

env:
  - NOT_CRAN=true
